In [55]:
import numpy as np
import scipy.stats as st
import scipy.optimize as opt

In [56]:
data = np.loadtxt('binomfreq.csv', skiprows=1, delimiter=',')
k = data[:,0]
absfreq = data[:,1]

In [57]:
N = sum(absfreq)
print (N)

407.0


In [58]:
relfreq = np.cumsum(absfreq/N)

In [59]:
relfreq

array([0.        , 0.002457  , 0.01228501, 0.05159705, 0.15970516,
       0.35626536, 0.6019656 , 0.82309582, 0.94594595, 0.99017199,
       1.        ])

### least square method

In [60]:
n = 10
def residu(p):
    return st.binom.cdf(k, n, p) - relfreq

lsqsol = opt.least_squares(residu, 0.6)
lsqsol.x

array([0.60530003])

### minimize method

In [61]:
def model(p):
    return np.sum(residu(p)**2)

minmodel = opt.minimize(model, 0.6)
minmodel.x


array([0.60530002])

### curve fit

In [62]:
def func(k, p):
    return st.binom.cdf(k, n, p)

params, _ = opt.curve_fit(func, k, relfreq, 0.6)
print (params)

[0.60530003]
