In [6]:
import numpy as np
import scipy.stats as st
import scipy.optimize as opt

In [7]:
data = np.loadtxt('poissonfreq.csv', skiprows=1, delimiter=',')
k = data[:,0]
absfreq = data[:,1]

In [8]:
N = sum(absfreq)
print (N)

689.0


In [9]:
relfreq = np.cumsum(absfreq/N)

In [10]:
relfreq

array([0.        , 0.        , 0.        , 0.00145138, 0.00580552,
       0.01886792, 0.04499274, 0.08998549, 0.15674891, 0.24528302,
       0.35123367, 0.46734398, 0.58490566, 0.69230769, 0.78374456,
       0.8563135 , 0.91146589, 0.94920174, 0.97387518, 0.98984035,
       1.        ])

### least square method

In [13]:
def residu(lam):
    return st.poisson.cdf(k, lam) - relfreq

lsqsol = opt.least_squares(residu, 12)
lsqsol.x

array([11.91295254])

### minimize method

In [14]:
def model(lam):
    return np.sum(residu(lam)**2)

minmodel = opt.minimize(model, 12)
minmodel.x


array([11.91295265])

### curve fit

In [15]:
def func(k, lam):
    return st.poisson.cdf(k, lam)

params, _ = opt.curve_fit(func, k, relfreq, 12)
print (params)

[11.91295254]
